"""Gemini TTS adapter — cloud expressive narration synthesis (preview).

Gemini 3.1 Flash TTS produces natural, emotionally-directed speech that
Edge-TTS's neural voices cannot match ("robot voice" complaint). It is
an ONLINE engine on a PREVIEW model, so it is strictly opt-in
(tts_engine="gemini") and the dispatcher in tts.py always falls back to
the default Edge → Piper → XTTS chain on any failure — a Gemini outage,
missing SDK, or exhausted quota never loses a render's narration.

Design mirrors tts_piper.py:
  - Hash-based synthesis cache (TEMP_DIR/gemini_tts_cache/) — identical
    text never hits the API twice, which also protects preview quota.
  - Raw PCM (s16le / 24 kHz / mono) → WAV → MP3 via FFmpeg so the output
    contract matches Edge/Piper/XTTS.
  - Raises RuntimeError on any failure — the caller falls back.

Two Gemini-specific notes:
  - Delivery is steered by a natural-language style instruction prefixed
    to the text (resolved per content_type; GEMINI_TTS_STYLE overrides).
    The ``rate`` knob used by Edge does not apply — the model paces itself.
  - All generated audio carries Google's inaudible SynthID watermark
    (detectable as AI-generated by platforms). Acceptable for narration;
    documented so nobody is surprised.
"""
from __future__ import annotations

import hashlib
import importlib.util
import logging
import os
import shutil
import subprocess
import threading
import time
import wave
from pathlib import Path

logger = logging.getLogger(__name__)


def _tts_model() -> str:
    """Resolve the TTS model at CALL time, not import time — this module can
    be imported before app.core.config has loaded .env (tools/tests), which
    would freeze the hardcoded default into the cache key."""
    return os.environ.get("GEMINI_TTS_MODEL", "gemini-3.1-flash-tts-preview")


# TTS-family model-fallback chain: when the primary TTS model is exhausted
# across every key by overload (503) / quota (429), the key-pool rotates DOWN
# this chain to the next TTS model (e.g. ``gemini-3.1-flash-tts-preview`` →
# ``gemini-2.5-flash-preview-tts``). Override via ``GEMINI_TTS_MODEL_FALLBACKS``
# (comma-separated). TTS family ONLY — never a text/image model.
_GEMINI_TTS_MODEL_FALLBACKS_ENV = "GEMINI_TTS_MODEL_FALLBACKS"
_DEFAULT_TTS_MODEL_FALLBACKS = ["gemini-2.5-flash-preview-tts"]


_GEMINI_TTS_TIMEOUT_SEC = int(os.environ.get("GEMINI_TTS_TIMEOUT_SEC", "120"))
# API contract for TTS models: raw PCM signed 16-bit LE, 24 kHz, mono.
_GEMINI_TTS_SAMPLE_RATE = 24000

# O-4: parts render in parallel, so per-part TTS calls would otherwise burst
# the preview model's low RPM — a burst of 429s (post-O-1) would cool pool
# keys needlessly. Same remedy as the rewrite path's _REWRITE_SEMAPHORE.
_GEMINI_TTS_MAX_CONCURRENCY = max(1, int(os.environ.get("GEMINI_TTS_MAX_CONCURRENCY", "2") or 2))
_GEMINI_TTS_SEMAPHORE = threading.Semaphore(_GEMINI_TTS_MAX_CONCURRENCY)

# gender → prebuilt Gemini voice. GEMINI_TTS_VOICE overrides both.
_VOICE_BY_GENDER = {
    "female": "Kore",
    "male": "Charon",
    "default": "Kore",
}

# content_type → delivery instruction. The model reads this as direction,
# not as text to speak. Listening A/B (2026-07-02) showed instructions in
# the NARRATION language produce noticeably better prosody than English
# ones on Vietnamese text, and explicit tempo words measurably control
# speed (same text: "nhanh vừa" ≈ 21s vs "chậm rãi" ≈ 30s). So styles are
# per-language tables with tempo baked in; English is the fallback for
# languages without a table.
_STYLE_BY_CONTENT_TYPE_VI = {
    "commentary": "Đọc bằng giọng bình luận sôi nổi, năng lượng cao, tốc độ nhanh, cuốn hút",
    "vlog":       "Đọc bằng giọng trò chuyện tự nhiên, ấm áp, tốc độ vừa phải",
    "story":      ("Bạn là người dẫn chuyện phim chuyên nghiệp. Đọc bằng giọng kể trầm ấm, "
                   "truyền cảm, tốc độ nhanh vừa phải và cuốn hút — không rề rà, không đều đều. "
                   "Nhấn mạnh từ khóa quan trọng, ngắt nghỉ ngắn tự nhiên giữa các câu, "
                   "đẩy kịch tính lên ở cao trào"),
    "tutorial":   "Đọc bằng giọng hướng dẫn rõ ràng, điềm tĩnh, tốc độ chậm vừa",
    "interview":  "Đọc bằng giọng điềm đạm, sâu lắng, có suy ngẫm",
    "montage":    "Đọc bằng giọng hype nhanh, năng lượng bùng nổ",
    "gaming":     "Đọc bằng giọng phấn khích, nhanh, năng lượng cao",
}
_STYLE_BY_CONTENT_TYPE_EN = {
    "commentary": "Read in an energetic, engaging commentary voice at a fast pace",
    "vlog":       "Read in a natural, warm conversational voice at a moderate pace",
    "story":      ("You are a professional film narrator. Read in a warm, expressive "
                   "storytelling voice at a brisk but comfortable pace — never flat or "
                   "monotonous. Stress key words, take short natural pauses between "
                   "sentences, build intensity at dramatic moments"),
    "tutorial":   "Read in a clear, calm, instructional voice at a measured pace",
    "interview":  "Read in a measured, thoughtful voice",
    "montage":    "Read in a fast, high-energy hype voice",
    "gaming":     "Read in a fast, excited, high-energy voice",
}
_STYLE_BY_CONTENT_TYPE_KO = {
    "commentary": "활기차고 몰입감 있는 해설 목소리로 빠른 속도로 읽어주세요",
    "vlog":       "자연스럽고 따뜻한 대화체 목소리로 적당한 속도로 읽어주세요",
    "story":      ("당신은 전문 영화 내레이터입니다. 따뜻하고 감정이 풍부한 목소리로, "
                   "늘어지거나 단조롭지 않게 적당히 빠른 속도로 읽어주세요. 중요한 단어를 "
                   "강조하고, 문장 사이에 짧고 자연스러운 쉼을 두고, 클라이맥스에서 "
                   "긴장감을 높여주세요"),
    "tutorial":   "명확하고 차분한 설명 목소리로 약간 느린 속도로 읽어주세요",
    "interview":  "차분하고 사려 깊은 목소리로 읽어주세요",
    "montage":    "빠르고 에너지 넘치는 하이프 목소리로 읽어주세요",
    "gaming":     "신나고 빠르며 에너지 넘치는 목소리로 읽어주세요",
}
_STYLE_BY_CONTENT_TYPE_JA = {
    "commentary": "エネルギッシュで引き込まれる実況の声で、速いテンポで読んでください",
    "vlog":       "自然で温かい会話調の声で、ほどよいテンポで読んでください",
    "story":      ("あなたはプロの映画ナレーターです。温かく感情豊かな声で、間延びせず"
                   "単調にならないよう、やや速めの心地よいテンポで読んでください。"
                   "重要な言葉を強調し、文と文の間に短く自然な間を置き、"
                   "クライマックスで緊張感を高めてください"),
    "tutorial":   "明確で落ち着いた解説の声で、ややゆっくり読んでください",
    "interview":  "落ち着いた思慮深い声で読んでください",
    "montage":    "速くてエネルギー全開のハイプな声で読んでください",
    "gaming":     "興奮した速いテンポでエネルギッシュに読んでください",
}
# language prefix → style table. Fallback: English.
_STYLE_TABLES = {
    "vi": _STYLE_BY_CONTENT_TYPE_VI,
    "ko": _STYLE_BY_CONTENT_TYPE_KO,
    "ja": _STYLE_BY_CONTENT_TYPE_JA,
}
# language prefix → (fast_strong, fast_slight, slow_strong, slow_slight)
# tempo directions for the explicit creator rate override.
_TEMPO_HINTS = {
    "vi": ("Tăng tốc độ đọc nhanh hơn rõ rệt.", "Đọc nhanh hơn một chút.",
           "Đọc chậm rãi hơn rõ rệt.", "Đọc chậm lại một chút."),
    "ko": ("훨씬 더 빠르게 읽어주세요.", "조금 더 빠르게 읽어주세요.",
           "훨씬 더 천천히 읽어주세요.", "조금 더 천천히 읽어주세요."),
    "ja": ("かなり速く読んでください。", "少し速く読んでください。",
           "かなりゆっくり読んでください。", "少しゆっくり読んでください。"),
    "en": ("Read noticeably faster.", "Read slightly faster.",
           "Read noticeably slower.", "Read slightly slower."),
}

# Guards the disk-cache check/copy against parallel parts synthesizing the
# same text. (O-3: the former in-memory dict here was write-only dead code —
# the disk file IS the cache.)
_GEMINI_CACHE_LOCK = threading.Lock()


def _resolve_api_key() -> str:
    """Return a Gemini API key: rotation pool first, then config/env.
    Never raises — returns '' when unset (caller treats as unavailable)."""
    try:
        from app.features.render.ai.llm.key_pool import active_key
        key = active_key()
        if key:
            return key
    except Exception:
        pass
    try:
        from app.core import config as _cfg
        key = getattr(_cfg, "GEMINI_API_KEY", "")
        if key:
            return key
    except Exception:
        pass
    return os.environ.get("GEMINI_API_KEY", "")


def gemini_tts_available() -> bool:
    """True when the google-genai SDK is importable AND an API key exists.

    Never raises — used by the dispatcher to decide whether Gemini TTS is
    viable before attempting synthesis.
    """
    try:
        if importlib.util.find_spec("google.genai") is None:
            return False
        return bool(_resolve_api_key())
    except Exception:
        return False


def _resolve_voice(gender: str) -> str:
    env = (os.environ.get("GEMINI_TTS_VOICE") or "").strip()
    if env:
        return env
    g = str(gender or "").strip().lower()
    return _VOICE_BY_GENDER.get(g, _VOICE_BY_GENDER["default"])


def _lang_prefix(language: str) -> str:
    return str(language or "").strip().lower().split("-")[0]


def _rate_to_tempo_hint(rate: str, lang: str) -> str:
    """Map an explicit creator rate ("+10%" / "-8%") to a tempo direction.

    Content-type styles already carry a baseline tempo, so a hint is added
    only for a deliberate creator override (|rate| ≥ 3%) — never for the
    "+0%" default. Returns '' when no hint applies. Never raises."""
    try:
        pct = int(str(rate or "").strip().replace("%", "").replace("+", "") or 0)
    except Exception:
        return ""
    hints = _TEMPO_HINTS.get(lang, _TEMPO_HINTS["en"])
    if pct >= 8:
        return hints[0]
    if pct >= 3:
        return hints[1]
    if pct <= -8:
        return hints[2]
    if pct <= -3:
        return hints[3]
    return ""


# D1: AI emotion → a Gemini TTS style directive appended to the content-type
# style. "" / "normal" / unknown = no directive (inert). Gated by CONTENT_EMOTION_TTS.
_EMOTION_STYLE: dict[str, str] = {
    "excited": "with an excited, energetic tone",
    "happy": "in a cheerful, upbeat tone",
    "surprise": "with a surprised, animated tone",
    "motivating": "in a motivating, inspiring tone",
    "curious": "in a curious, inquisitive tone",
    "epic": "in an epic, dramatic tone",
    "suspense": "in a tense, suspenseful tone",
    "calm": "in a calm, soothing tone",
    "sad": "in a soft, sombre tone",
}


def _resolve_style(content_type: str, language: str = "", rate: str = "", emotion: str = "") -> str:
    env = (os.environ.get("GEMINI_TTS_STYLE") or "").strip()
    if env:
        return env
    lang = _lang_prefix(language)
    table = _STYLE_TABLES.get(lang, _STYLE_BY_CONTENT_TYPE_EN)
    style = table.get(str(content_type or "").strip().lower(), table["vlog"])
    hint = _rate_to_tempo_hint(rate, lang)
    style = f"{style}. {hint}" if hint else style
    if os.getenv("CONTENT_EMOTION_TTS", "1") == "1":
        em = _EMOTION_STYLE.get((emotion or "").strip().lower(), "")
        if em:
            style = f"{style}. Speak {em}"
    return style


def _wav_to_mp3(wav_path: Path, mp3_path: Path) -> None:
    """Convert WAV to MP3 via FFmpeg (libmp3lame, VBR quality 2 ≈ 190 kbps)."""
    from app.services.bin_paths import get_ffmpeg_bin
    cmd = [
        get_ffmpeg_bin(), "-y",
        "-i", str(wav_path),
        "-codec:a", "libmp3lame", "-q:a", "2",
        str(mp3_path),
    ]
    result = subprocess.run(cmd, capture_output=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(
            f"WAV→MP3 conversion failed: {result.stderr.decode(errors='replace')[:300]}"
        )


def _synthesis_cache_key(text: str, language: str, voice: str, style: str) -> str:
    """16-char SHA256 prefix — deterministic key for synthesized audio.
    Model id is part of the key so a model upgrade never serves stale audio."""
    payload = f"gemini\x00{_tts_model()}\x00{voice}\x00{style}\x00{language}\x00{text}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def _generate_pcm(style: str, text: str, voice: str) -> bytes:
    """Run the Gemini TTS call across the key pool — O-1.

    Routed through ``call_gemini_with_rotation`` exactly like the six LLM
    wrappers in providers/gemini.py: a 429 cools the key and retries the SAME
    request on the next key; a transient 503/504 retries on the next key
    without cooling. Without this, one exhausted key dropped the whole render
    to the Edge chain mid-video — parts switching voice — while other pool
    keys still had quota.

    Serialized by ``_GEMINI_TTS_SEMAPHORE`` (O-4) so parallel parts don't
    burst the preview model's RPM and cool keys needlessly.

    Returns raw PCM bytes; raises RuntimeError when every key is exhausted or
    the response is empty (caller falls back to the Edge chain).
    """
    from app.features.render.ai.llm.key_pool import (
        active_key, call_gemini_with_model_rotation, model_chain,
    )
    from google import genai  # lazy — optional dependency
    from google.genai import types as genai_types

    model = _tts_model()

    def _once(key: str, tts_model: str) -> "bytes | None":
        client = genai.Client(
            api_key=key,
            http_options={"timeout": _GEMINI_TTS_TIMEOUT_SEC * 1000},
        )
        resp = client.models.generate_content(
            model=tts_model,
            contents=f"{style}: {text}",
            config=genai_types.GenerateContentConfig(
                response_modalities=["AUDIO"],
                speech_config=genai_types.SpeechConfig(
                    voice_config=genai_types.VoiceConfig(
                        prebuilt_voice_config=genai_types.PrebuiltVoiceConfig(voice_name=voice)
                    )
                ),
            ),
        )
        try:
            pcm = resp.candidates[0].content.parts[0].inline_data.data
        except (AttributeError, IndexError, TypeError):
            return None  # empty response — non-retryable, rotation fails fast
        return pcm or None

    with _GEMINI_TTS_SEMAPHORE:
        pcm = call_gemini_with_model_rotation(
            _once, label="gemini-tts", seed_key=active_key(),
            models=model_chain(
                model,
                env_var=_GEMINI_TTS_MODEL_FALLBACKS_ENV,
                default_fallbacks=_DEFAULT_TTS_MODEL_FALLBACKS,
            ),
        )
    if not pcm:
        raise RuntimeError("gemini_tts_failed_all_keys_or_empty")
    return pcm


def synthesize_gemini(
    *,
    text: str,
    language: str,
    gender: str,
    job_id: str,
    content_type: str = "vlog",
    output_path: str | None = None,
    rate: str = "",
    emotion: str = "",
) -> str:
    """Synthesize speech with Gemini TTS (online, preview). Returns MP3 path.

    Raises RuntimeError on any failure — the caller must catch and fall
    back to the Edge → Piper → XTTS chain. Uses a hash-based cache:
    identical (text, language, voice, style, model) returns instantly and
    spends no API quota.
    """
    from app.core.config import TEMP_DIR

    clean_text = str(text or "").strip()
    if not clean_text:
        raise RuntimeError("Narration text is empty")

    if not _resolve_api_key():
        raise RuntimeError("gemini_tts_no_api_key")

    voice = _resolve_voice(gender)
    # Style (incl. any tempo hint) is part of the cache key downstream, so a
    # rate change correctly re-synthesizes instead of serving cached audio.
    style = _resolve_style(content_type, language=language, rate=rate, emotion=emotion)

    cache_key = _synthesis_cache_key(clean_text, language, voice, style)
    cache_dir = TEMP_DIR / "gemini_tts_cache"
    cached_mp3 = cache_dir / f"{cache_key}.mp3"
    with _GEMINI_CACHE_LOCK:
        if cached_mp3.exists() and cached_mp3.stat().st_size > 0:
            dest = Path(output_path) if output_path else (TEMP_DIR / job_id / "voice" / "narration.mp3")
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest != cached_mp3:
                shutil.copy2(str(cached_mp3), str(dest))
            logger.info("gemini_tts_cache_hit job_id=%s key=%s", job_id, cache_key)
            return str(dest)

    work_dir = TEMP_DIR / job_id / "voice"
    work_dir.mkdir(parents=True, exist_ok=True)
    wav_path = work_dir / "narration.gemini.wav"
    mp3_path = Path(output_path) if output_path else work_dir / "narration.mp3"
    mp3_path.parent.mkdir(parents=True, exist_ok=True)

    start = time.perf_counter()
    logger.info(
        "gemini_tts_start job_id=%s model=%s voice=%s language=%s content_type=%s chars=%d",
        job_id, _tts_model(), voice, language, content_type, len(clean_text),
    )

    # O-1: synthesis rides the key-rotation pool (429 → next key) under the
    # O-4 concurrency semaphore. Raises when every key is exhausted.
    pcm = _generate_pcm(style, clean_text, voice)

    with wave.open(str(wav_path), "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(_GEMINI_TTS_SAMPLE_RATE)
        wf.writeframes(pcm)

    if not wav_path.exists() or wav_path.stat().st_size <= 0:
        raise RuntimeError("Gemini TTS produced empty WAV output")

    _wav_to_mp3(wav_path, mp3_path)
    wav_path.unlink(missing_ok=True)

    if not mp3_path.exists() or mp3_path.stat().st_size <= 0:
        raise RuntimeError("Gemini TTS WAV→MP3 conversion produced empty file")

    # Store in shared cache for future reuse (the disk file IS the cache).
    try:
        cache_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(mp3_path), str(cached_mp3))
    except Exception as _cache_exc:
        logger.debug("gemini_tts_cache_write_failed key=%s: %s", cache_key, _cache_exc)

    audio_sec = len(pcm) / (_GEMINI_TTS_SAMPLE_RATE * 2)
    elapsed_ms = int((time.perf_counter() - start) * 1000)
    logger.info(
        "gemini_tts_complete job_id=%s model=%s voice=%s audio_sec=%.1f elapsed_ms=%d output=%s",
        job_id, _tts_model(), voice, audio_sec, elapsed_ms, mp3_path.name,
    )
    return str(mp3_path)
