"""test_content_scene_render.py — Content Mode engine (Phase 2).

Verifies the two new offline building blocks that let Content Mode composite a
scene WITHOUT any source footage:

  - content_background.build_background_clip  → a video-only background clip
  - content_scene_render.render_content_scene → background + burned subtitle +
    muxed narration audio, at the target A/V spec

Runs FULLY OFFLINE: the narration audio is a synthetic silent track generated by
FFmpeg (lavfi anullsrc), so no network / TTS engine is required. Also unit-tests
the pure helpers (SRT builder, reading-speed→rate mapping, color normalisation)
which need no FFmpeg at all.

Skip guard: the FFmpeg-dependent tests are skipped when FFmpeg is not on PATH.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from app.domain.content_plan import ContentScene
from app.features.render.engine.stages import content_background as cbg
from app.features.render.engine.stages import content_scene_render as csr


# ── Skip guard ───────────────────────────────────────────────────────────────

def _ffmpeg_ok() -> bool:
    try:
        from app.services.bin_paths import get_ffmpeg_bin
        r = subprocess.run([get_ffmpeg_bin(), "-version"], capture_output=True, timeout=5)
        return r.returncode == 0
    except Exception:
        return False


_FFMPEG = _ffmpeg_ok()
needs_ffmpeg = pytest.mark.skipif(not _FFMPEG, reason="FFmpeg not available on PATH")


def _probe(path: str) -> dict:
    """Return {'v': bool, 'a': bool, 'dur': float} for a media file via ffprobe."""
    from app.services.bin_paths import get_ffprobe_bin
    def _q(stream: str, entries: str) -> str:
        out = subprocess.run(
            [get_ffprobe_bin(), "-v", "error", "-select_streams", stream,
             "-show_entries", entries, "-of", "default=noprint_wrappers=1:nokey=1", path],
            capture_output=True, text=True, timeout=30,
        )
        return (out.stdout or "").strip()
    has_v = bool(_q("v:0", "stream=codec_type"))
    has_a = bool(_q("a:0", "stream=codec_type"))
    dur_raw = _q("v:0", "stream=duration") or ""
    if not dur_raw:
        fout = subprocess.run(
            [get_ffprobe_bin(), "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", path],
            capture_output=True, text=True, timeout=30,
        )
        dur_raw = (fout.stdout or "").strip()
    try:
        dur = float(dur_raw)
    except (TypeError, ValueError):
        dur = 0.0
    return {"v": has_v, "a": has_a, "dur": dur}


def _make_silent_audio(path: str, seconds: float, sr: int = 48000) -> None:
    from app.services.bin_paths import get_ffmpeg_bin
    subprocess.run(
        [get_ffmpeg_bin(), "-y", "-f", "lavfi",
         "-i", f"anullsrc=channel_layout=stereo:sample_rate={sr}",
         "-t", f"{seconds:.3f}", "-c:a", "libmp3lame", path],
        capture_output=True, check=True, timeout=60,
    )


# ── Pure-helper unit tests (no FFmpeg) ───────────────────────────────────────

def test_normalize_color():
    assert cbg._normalize_color("#1e90ff") == "0x1e90ff"
    assert cbg._normalize_color("#000000") == "0x000000"
    assert cbg._normalize_color("black") == "black"
    assert cbg._normalize_color("") == "0x000000"
    assert cbg._normalize_color("not-a-color!") == "not-a-color!"  # passthrough token
    assert cbg._normalize_color("#zzzzzz") == "0x000000"  # invalid hex → black


def test_reading_speed_to_rate():
    assert csr._reading_speed_to_rate(1.0) == "+0%"
    assert csr._reading_speed_to_rate(1.1) == "+10%"
    assert csr._reading_speed_to_rate(0.9) == "-10%"
    assert csr._reading_speed_to_rate(9.0) == "+100%"   # clamp 2.0 → +100%
    assert csr._reading_speed_to_rate("bad") == "+0%"


def test_build_scene_srt(tmp_path):
    srt = tmp_path / "s.srt"
    ok = csr._build_scene_srt(
        "First sentence here. Second one follows! And a third.", 0.5, 6.0, str(srt),
    )
    assert ok and srt.exists()
    body = srt.read_text(encoding="utf-8")
    assert "-->" in body
    assert "00:00:00,500 -->" in body  # honours the start offset
    # empty narration → no file / False
    assert csr._build_scene_srt("", 0.0, 3.0, str(tmp_path / "e.srt")) is False


def test_split_cues_caps_count():
    text = ". ".join(f"sentence number {i}" for i in range(20)) + "."
    cues = csr._split_cues(text, 6)
    assert 0 < len(cues) <= 6


# ── FFmpeg composition tests (offline, synthetic audio) ──────────────────────

@needs_ffmpeg
def test_build_background_clip_color(tmp_path):
    out = tmp_path / "bg.mp4"
    ok = cbg.build_background_clip(
        kind="color", value="#101820", width=320, height=568, fps=30,
        duration_sec=2.0, out_path=str(out),
    )
    assert ok and out.exists()
    info = _probe(str(out))
    assert info["v"] is True, "background must have a video stream"
    assert info["a"] is False, "background must be video-only (no audio track)"
    assert 1.6 <= info["dur"] <= 2.6, f"duration off: {info['dur']}"


def _make_image(path: str, w: int = 640, h: int = 480) -> None:
    from app.services.bin_paths import get_ffmpeg_bin
    subprocess.run(
        [get_ffmpeg_bin(), "-y", "-f", "lavfi", "-i", f"color=c=red:s={w}x{h}",
         "-frames:v", "1", path],
        capture_output=True, check=True, timeout=30,
    )


@needs_ffmpeg
def test_build_background_clip_image_ken_burns(tmp_path):
    img = tmp_path / "bg.png"
    _make_image(str(img))
    out = tmp_path / "kb.mp4"
    ok = cbg.build_background_clip(
        kind="image", value=str(img), width=320, height=568, fps=30,
        duration_sec=2.0, out_path=str(out), ken_burns=True,
    )
    assert ok and out.exists()
    info = _probe(str(out))
    assert info["v"] is True and info["a"] is False
    assert 1.5 <= info["dur"] <= 2.6, f"duration off: {info['dur']}"


@needs_ffmpeg
def test_build_background_clip_missing_asset_returns_false(tmp_path):
    out = tmp_path / "bg2.mp4"
    ok = cbg.build_background_clip(
        kind="image", value=str(tmp_path / "does_not_exist.png"),
        width=320, height=568, fps=30, duration_sec=1.0, out_path=str(out),
    )
    assert ok is False and not out.exists()


@needs_ffmpeg
def test_render_content_scene_composites_av(tmp_path):
    narration_dur = 3.0
    audio = tmp_path / "narr.mp3"
    _make_silent_audio(str(audio), narration_dur, sr=48000)

    scene = ContentScene(
        index=0, role="hook",
        narration="Xin chao cac ban. Hom nay chung ta tim hieu ve Sao Hoa. That thu vi!",
        emotion="curious", reading_speed=1.0, pause_before=0.4, pause_after=0.6,
    )
    out = tmp_path / "scene_000.mp4"
    ok = csr.render_content_scene(
        scene=scene, background_kind="color", background_value="#000000",
        narration_audio_path=str(audio), narration_dur=narration_dur,
        width=320, height=568, fps=30, sample_rate=48000,
        out_path=str(out), work_dir=str(tmp_path / "work"), subtitle_enabled=True,
    )
    assert ok and out.exists(), "scene render must succeed"
    info = _probe(str(out))
    assert info["v"] is True, "scene must have a video stream"
    assert info["a"] is True, "scene must have an audio stream"
    expected = 0.4 + narration_dur + 0.6  # pause_before + narration + pause_after
    assert abs(info["dur"] - expected) <= 0.6, f"scene duration {info['dur']} vs ~{expected}"


# ── CS-C: word-by-word subtitle ──────────────────────────────────────────────

def test_shift_srt(tmp_path):
    srt = tmp_path / "w.srt"
    srt.write_text(
        "1\n00:00:00,000 --> 00:00:00,400\nHello\n\n"
        "2\n00:00:00,400 --> 00:00:00,900\nworld\n\n",
        encoding="utf-8",
    )
    csr._shift_srt(str(srt), 0.5)
    body = srt.read_text(encoding="utf-8")
    assert "00:00:00,500 --> 00:00:00,900" in body  # first cue shifted +0.5
    assert "00:00:00,900 --> 00:00:01,400" in body  # second cue shifted +0.5


def test_build_word_ass_returns_false_when_whisper_unavailable(tmp_path, monkeypatch):
    def _boom(*a, **k):
        raise RuntimeError("whisper not installed")
    monkeypatch.setattr(
        "app.features.render.engine.subtitle.transcription.whisper.transcribe_to_srt", _boom,
    )
    ok = csr._build_word_ass(
        str(tmp_path / "a.mp3"), str(tmp_path / "o.ass"),
        1080, 1920, "capcut_box", "base", 0.0,
    )
    assert ok is False


@needs_ffmpeg
def test_render_scene_word_by_word_burns_ass(tmp_path, monkeypatch):
    """With word-by-word ON and Whisper mocked to emit a word-level SRT, the scene
    renders via the CapCut ASS path (real srt_to_ass_capcut) → valid A/V."""
    narration_dur = 2.0
    audio = tmp_path / "narr.mp3"
    _make_silent_audio(str(audio), narration_dur, sr=48000)

    def _fake_transcribe(video_path, srt_path, model_name="base", retry_count=2, highlight_per_word=False):
        # Word-level SRT (what highlight_per_word=True would produce).
        Path(srt_path).write_text(
            "1\n00:00:00,000 --> 00:00:00,500\nXin\n\n"
            "2\n00:00:00,500 --> 00:00:01,000\nchao\n\n"
            "3\n00:00:01,000 --> 00:00:01,800\nban\n\n",
            encoding="utf-8",
        )
    monkeypatch.setattr(
        "app.features.render.engine.subtitle.transcription.whisper.transcribe_to_srt",
        _fake_transcribe,
    )
    monkeypatch.setattr(csr, "_CONTENT_WORD_BY_WORD", True, raising=False)

    scene = ContentScene(index=0, role="hook", narration="Xin chao ban",
                         reading_speed=1.0, pause_before=0.3)
    out = tmp_path / "scene_wbw.mp4"
    ok = csr.render_content_scene(
        scene=scene, background_kind="color", background_value="#000000",
        narration_audio_path=str(audio), narration_dur=narration_dur,
        width=320, height=568, fps=30, sample_rate=48000,
        out_path=str(out), work_dir=str(tmp_path / "work"), subtitle_enabled=True,
        subtitle_style="capcut_box",
    )
    assert ok and out.exists(), "word-by-word scene render must succeed"
    info = _probe(str(out))
    assert info["v"] and info["a"], "scene must have video + audio"


# ── CS-F: BGM mix + ducking ──────────────────────────────────────────────────

@needs_ffmpeg
def test_mix_with_bgm_duck(tmp_path):
    from app.features.render.engine.audio.mixer import mix_with_bgm
    from app.services.bin_paths import get_ffmpeg_bin
    vid = tmp_path / "v.mp4"
    subprocess.run(
        [get_ffmpeg_bin(), "-y", "-f", "lavfi", "-i", "color=c=blue:s=320x240:d=2",
         "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo", "-t", "2",
         "-c:v", "libx264", "-c:a", "aac", str(vid)],
        capture_output=True, check=True, timeout=60,
    )
    bgm = tmp_path / "bgm.mp3"
    _make_silent_audio(str(bgm), 3.0)  # shorter/looped BGM path exercised
    out = tmp_path / "mixed.mp4"
    res = mix_with_bgm(video_path=str(vid), bgm_path=str(bgm), output_path=str(out), duck=True)
    assert Path(res).exists()
    info = _probe(str(out))
    assert info["v"] is True and info["a"] is True
    assert 1.6 <= info["dur"] <= 2.6, f"duration off: {info['dur']}"


@needs_ffmpeg
def test_render_content_scene_missing_audio_returns_false(tmp_path):
    scene = ContentScene(index=1, narration="something", reading_speed=1.0)
    out = tmp_path / "scene_bad.mp4"
    ok = csr.render_content_scene(
        scene=scene, background_kind="color", background_value="#000000",
        narration_audio_path=str(tmp_path / "nope.mp3"), narration_dur=2.0,
        width=320, height=568, fps=30, sample_rate=48000,
        out_path=str(out), work_dir=str(tmp_path / "work2"), subtitle_enabled=True,
    )
    assert ok is False and not out.exists()
