"""
plan_stage.py — resolve + refine + fit + audit the ContentPlan (CM-6 extract).

Returns a usable ContentPlan (>=1 scene) or raises RuntimeError. Byte-for-byte
the former inline block in run_content: CM-3 persisted-plan-on-resume →
content_plan_override → AI Director; then the opt-in narration refine, the
deterministic duration fit, and the diagnostic narration audit. Emits the same
WS events / logs; ``set_stage`` is passed in (the pipeline's stage emitter).
"""
from __future__ import annotations

import logging
import os

from app.core.stage import JobStage
from app.domain.content_plan import ContentPlan
from app.features.render.ai.llm import select_content_plan
from app.features.render.engine.pipeline.render_events import _emit_render_event, _job_log

logger = logging.getLogger("app.render.content")


def resolve_content_plan(payload, *, job_id, effective_channel, resume_mode, script, language, set_stage):
    """Produce the ContentPlan the render will use. Raises RuntimeError when no
    usable plan can be obtained (Sacred Contract #3 — the AI path returns None)."""
    # 3. Content Plan — either an APPROVED plan from the Review step
    #    (content_plan_override), or freshly generated by the AI Director.
    set_stage(JobStage.ANALYZING, 15, "Preparing content plan")
    plan = None
    # CM-3: on resume, the persisted ContentPlan is the CHECKPOINT — the scenes
    # already rendered on disk are keyed by ITS index order. Prefer it over the
    # override/AI path so resume reuses those scenes instead of re-planning
    # (which could reorder/reindex and orphan the disk-truth scenes, esp. when
    # the original run planned via AI and the stored payload has no override).
    # Defensive: a missing/unusable persisted plan falls through unchanged.
    if resume_mode:
        try:
            from app.db.jobs_repo import get_content_plan
            _persisted = get_content_plan(job_id)
            if _persisted:
                _rp = ContentPlan.from_json(_persisted)
                if _rp is not None and _rp.scene_count() > 0:
                    plan = _rp
                    _job_log(effective_channel, job_id,
                             f"Content: resuming from persisted plan "
                             f"({plan.scene_count()} scene(s)) — planning skipped")
        except Exception as _rexc:
            logger.warning("content: resume plan load failed (%s) — normal planning", _rexc)
    _override_raw = (getattr(payload, "content_plan_override", "") or "").strip()
    if plan is None and _override_raw:
        # CS-A: render FROM the user-approved/edited plan — skip the AI call.
        plan = ContentPlan.from_json(_override_raw)
        if plan is not None and plan.scene_count() > 0:
            _job_log(effective_channel, job_id,
                     f"Content: using approved plan ({plan.scene_count()} scene(s)) — AI planning skipped")
        else:
            # Defensive: a malformed override falls back to AI planning rather
            # than failing the job (Sacred Contract #3 spirit).
            logger.warning("content: content_plan_override unusable — falling back to AI planning")
            plan = None
    if plan is None:
        from app.core import config as _cfg
        from app.features.render.engine.pipeline.llm_stage import _resolve_api_key
        provider = (getattr(payload, "ai_provider", "") or "").strip().lower() \
            or getattr(_cfg, "AI_PROVIDER_DEFAULT", "gemini")
        api_key, _ = _resolve_api_key(payload, provider)
        plan = select_content_plan(
            provider=provider, script=script,
            target_duration_sec=float(getattr(payload, "target_duration", 90) or 90),
            target_language=language, tone=(getattr(payload, "rewrite_tone", "") or ""),
            api_key=api_key, model=getattr(payload, "llm_model", None),
            # LOW-1: resolve the right key per provider on cross-provider fallback.
            resolve_key=lambda _prov: _resolve_api_key(payload, _prov)[0],
        )
    if plan is None or plan.scene_count() == 0:
        raise RuntimeError("Content: no usable content plan")

    # Content per-scene narration refine (opt-in, CONTENT_REFINE_NARRATION=1
    # — default OFF because it costs +1 LLM call). A focused second pass
    # re-authors the whole scene set's narration so voice-over flows
    # scene→scene and each scene's length matches its planned seconds.
    # Best-effort: any failure keeps the original narration (Sacred #3 spirit).
    # Runs BEFORE the duration fit so the fit measures the final narration.
    if os.getenv("CONTENT_REFINE_NARRATION", "0") == "1":
        try:
            from app.features.render.ai.llm import select_content_narration
            from app.core import config as _cfg2
            from app.features.render.engine.pipeline.llm_stage import _resolve_api_key
            _prov = (getattr(payload, "ai_provider", "") or "").strip().lower() \
                or getattr(_cfg2, "AI_PROVIDER_DEFAULT", "gemini")
            _key, _ = _resolve_api_key(payload, _prov)
            _scene_payload = [
                {
                    "index": i, "role": (s.role or ""),
                    "seconds": float(getattr(s, "est_duration_sec", 0.0) or 0.0),
                    "narration": (s.narration or ""),
                }
                for i, s in enumerate(plan.scenes)
            ]
            _refined = select_content_narration(
                provider=_prov, scenes=_scene_payload,
                topic=(plan.topic or ""), tone=(plan.tone or getattr(payload, "rewrite_tone", "") or ""),
                target_language=language, api_key=_key,
                model=getattr(payload, "llm_model", None),
            )
            if _refined:
                _n_refined = 0
                for i, s in enumerate(plan.scenes):
                    _txt = _refined.get(i)
                    if _txt and _txt.strip():
                        s.narration = _txt.strip()
                        _n_refined += 1
                if _n_refined:
                    _job_log(effective_channel, job_id,
                             f"Content: narration refined ({_n_refined} scene(s))")
                    _emit_render_event(
                        channel_code=effective_channel, job_id=job_id,
                        event="content.narration.refined", level="INFO",
                        message=f"Per-scene narration refined ({_n_refined} scene(s))",
                        step="render.content", context={"scenes_refined": _n_refined},
                    )
        except Exception as _refine_exc:
            logger.warning("content: narration refine failed (non-fatal): %s", _refine_exc)

    # Deterministic duration fit (mirrors recap's trim_to_duration_band in
    # spirit): the AI's est_duration_sec often drifts from the requested
    # target. Uniformly scale reading_speed (clamped) so the video lands near
    # target WITHOUT dropping any narrative scene. Non-destructive, never
    # raises, env kill-switch CONTENT_FIT_DURATION (default ON). Runs BEFORE
    # persist + part seeding so narration/TTS use the fitted speeds.
    if os.getenv("CONTENT_FIT_DURATION", "1") == "1":
        try:
            _target = float(getattr(payload, "target_duration", 0) or 0)
            _fit = plan.fit_to_target_duration(_target)
            if _fit.get("changed"):
                _job_log(
                    effective_channel, job_id,
                    f"Content: fitted to target — {_fit['before_sec']:.0f}s → "
                    f"{_fit['after_sec']:.0f}s (target {_fit['target_sec']:.0f}s, "
                    f"speed ×{_fit.get('applied_scale')}, {_fit['scaled_scenes']} scene(s))",
                )
                _emit_render_event(
                    channel_code=effective_channel, job_id=job_id,
                    event="content.timing.fit", level="INFO",
                    message=(
                        f"Content fitted to target: {_fit['before_sec']:.0f}s → "
                        f"{_fit['after_sec']:.0f}s"
                    ),
                    step="render.content", context=_fit,
                )
        except Exception as _fit_exc:
            logger.warning("content: duration fit failed (non-fatal): %s", _fit_exc)

    # Deterministic narration/timing audit (diagnostic only — mirrors recap's
    # coverage check). Flags scenes whose narration is too long ("overloaded"
    # → TTS rushes/overflows) or too short ("sparse" → silence) for their
    # planned duration. Never blocks the render; emits a WS event + logs a
    # warning so a weak plan is visible. Runs on the FITTED plan.
    try:
        _audit = plan.narration_audit()
        _emit_render_event(
            channel_code=effective_channel, job_id=job_id,
            event="content.narration.audit",
            level=("WARNING" if _audit.get("weak") else "INFO"),
            message=(
                f"Narration audit: {_audit['overloaded']} overloaded, "
                f"{_audit['sparse']} sparse of {_audit['rated']} rated scene(s)"
                + (" — weak plan" if _audit.get("weak") else "")
            ),
            step="render.content", context=_audit,
        )
        if _audit.get("weak"):
            _job_log(
                effective_channel, job_id,
                f"content_narration_weak overloaded={_audit['overloaded']} "
                f"sparse={_audit['sparse']}/{_audit['rated']} — narration/timing mismatch",
                kind="warning",
            )
    except Exception as _audit_exc:
        logger.warning("content: narration audit failed (non-fatal): %s", _audit_exc)

    return plan
